// Generates the app and tray icons from assets/icon.svg.
//
// This is a dev-only tool and is intentionally NOT wired into the normal
// build. Its outputs (assets/icon.ico, assets/icon.png, src/tray-icon.js and
// assets/social.png) are committed, so regular builds and CI never need the
// heavy image deps.
//
// To regenerate after editing assets/icon.svg, install the two dev-only tools
// (kept out of package.json to keep CI light) and run this script:
//
//   npm install --no-save sharp png-to-ico
//   node scripts/make-icons.js
//   git checkout -- package-lock.json   # discard lockfile churn from --no-save

const fs = require("fs");
const path = require("path");
const sharp = require("sharp");
const pngToIcoModule = require("png-to-ico");
const pngToIco = pngToIcoModule.default || pngToIcoModule;

const root = path.join(__dirname, "..");
const assetsDir = path.join(root, "assets");
const svgPath = path.join(assetsDir, "icon.svg");
const socialSvgPath = path.join(assetsDir, "social.svg");

async function png(size, outPath) {
  const buf = await sharp(svgPath, { density: 384 })
    .resize(size, size, {
      fit: "contain",
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    })
    .png()
    .toBuffer();
  if (outPath) fs.writeFileSync(outPath, buf);
  return buf;
}

(async () => {
  // App icon master PNG.
  await png(512, path.join(assetsDir, "icon.png"));

  // Windows .ico with the standard set of sizes (used by build.win.icon).
  const sizes = [16, 24, 32, 48, 64, 128, 256];
  const buffers = await Promise.all(sizes.map((s) => png(s)));
  const ico = await pngToIco(buffers);
  fs.writeFileSync(path.join(assetsDir, "icon.ico"), ico);

  // Tray icon, embedded as base64 in src/tray-icon.js so the packaged app
  // needs no external asset. 32px reads well in the Windows notification area.
  const tray = await png(32);
  const js =
    "// AUTO-GENERATED by scripts/make-icons.js from build/icon.svg. Do not edit.\n" +
    'module.exports =\n  "' +
    tray.toString("base64") +
    '";\n';
  fs.writeFileSync(path.join(root, "src", "tray-icon.js"), js);

  // GitHub social preview banner (recommended 1280x640).
  await sharp(socialSvgPath, { density: 144 })
    .resize(1280, 640)
    .png()
    .toFile(path.join(assetsDir, "social.png"));

  console.log(
    "Generated assets/icon.png, assets/icon.ico, src/tray-icon.js, assets/social.png",
  );
})().catch((e) => {
  console.error(e);
  process.exit(1);
});
